import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { getProducts } from "../src/database/model";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const products = await getProducts();
  return {
    props: {
      products,
    },
  };
}

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Emotion For Sale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Emotion
          
        </h1>
        <p>Welcome to out page, where you can bag yourself some Emotions!</p>
        <ul>
          {products.map((product) => (
            <li key={product.id} className={styles.card}>
              <h2>{product.name}</h2>
              <p className={styles.description}>{product.description}</p>
              <p>{product.price}</p>

              <Image
                src={product.image}
                alt={product.name}
                width={500}
                height={350}
              />
            </li>
          ))}
        </ul>
    
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
