import Head from "next/head";
import Image from "next/image";
import { getProducts } from "../src/database/model";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const products = await getProducts();
  return {
    props: {
      products,
    },
  };
}

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Emotion For Sale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to out page, where you can bag yourself some Emotions!
        </h1>

        <nav>
<input type="text" name="text" className={styles.input}></input>
<button className={styles.button}>Click to add</button>

        </nav>
        <div className={styles.products}>
        <ul>
          {products.map((product) => (
            <li key={product.id}>
              <h2>{product.name}</h2>
              <p className={styles.description}>{product.description}</p>
              <p>{product.price}</p>
            </li>
          ))}
        </ul>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
